mouse/controller_manager:
  ros__parameters:
    update_rate: 1000

    mouse_motors:
      type: diff_drive_controller/DiffDriveController

    mouse_joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster

mouse/mouse_motors:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link
    odom_frame_id: odom

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.6
    wheel_radius: 0.1

    use_stamped_vel: False