<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="landmine">

  <xacro:arg name="width" default="1" />
  <xacro:arg name="height" default="1" />
  <xacro:arg name="depth" default="1" />
  <xacro:arg name="topic" default="trigger0" />

  <link name="mine_link">
    <visual>
      <geometry>
        <box size="$(arg width) $(arg height) $(arg depth)"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision name="front_bumper_collision">
      <origin xyz="0.0 0.0 ${-$(arg depth)/2}" />
      <geometry>
        <box size="$(arg width) $(arg height) 0.2"/>
      </geometry>

    <!-- <surface>
        <contact>
          <collide_bitmask>0x0000</collide_bitmask>
          <collide_without_contact>true</collide_without_contact>
          <collide_without_contact_bitmask>0x0000</collide_without_contact_bitmask>
        </contact>
    </surface> -->

    </collision>
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.0833" ixy="0.0" ixz="0.0" iyy="0.0833" iyz="0.0" izz="0.0833"/>
    </inertial>
  </link>

  <gazebo>
    <static>true</static>
  </gazebo>


  <gazebo reference="mine_link">
    <material>Gazebo/Red</material>
    <static>true</static>    

    <sensor type="contact" name="contact_sensor">
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <contact>
        <collision>mine_link_fixed_joint_lump__front_bumper_collision_collision</collision>
      </contact>
      <plugin name="bumper_plugin" filename="libgazebo_ros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <frameName>mine_link</frameName>
          <ros>
          <remapping>/bumper_states:=/$(arg topic)</remapping>
          </ros>
      </plugin>
    </sensor>
  </gazebo>
</robot>
