version: '3.9'

networks:
  internal:
    name: "robal_internal"
  external:
    name: "robal_external"
    driver: bridge

services:

  ros:
    container_name: robal_ros2
    build:
      context: ./
      dockerfile: ./Docker/Dockerfile
    env_file:
      - ./env/env
    volumes:
      - ./src:/app/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - internal
      - external
    expose:
      - 3000
      - 5900
    ports:
      - 3000:22
      - 5900:5900
    
