version: '3.9'

networks:
  internal:
    name: "robal_internal"
  external:
    name: "robal_external"
    driver: bridge

services:


  control:
    container_name: kapibara_control
    build:
      dockerfile: ./Dockerfile
      context: ./control
    env_file:
      - ./control/env/env
    volumes:
      - ./control/commands/:/app/cmd
      - ./control/dependencies/:/app/dep
      - ./control/src:/app/src:rw
    networks:
      - internal
      - external

  gazebo:
    container_name: kapibara_gazebo
    build:
      dockerfile: ./Dockerfile
      context: ./gazebo
    env_file:
      - ./gazebo/env/env
    volumes:
      - ./gazebo/commands/:/app/cmd
      - ./gazebo/dependencies/:/app/dep
      - ./gazebo/src:/app/src:rw
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - internal
      - external

    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri/:/dev/dri/"

    group_add:
      - video
    
