version: '3.9'

networks:
  internal:
    name: "robal_internal"
  external:
    name: "robal_external"
    driver: bridge

services:

  ros:
    container_name: robal_ros2
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./env/env
    volumes:
      - ./commands/:/app/cmd
      - ./dependencies/:/app/dep
      - ./src:/app/src:rw
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - internal
      - external

    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri/:/dev/dri/"

    group_add:
      - video
    expose:
      - 5900
    ports:
      - 5900:5900
    
