controller_manager:
  ros__parameters:
    update_rate: 1000
    #use_sim_time: true

    motors:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    ears_controller:
      type: position_controllers/JointGroupPositionController


motors:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['wheel_left1_joint']
    right_wheel_names: ['wheel_right3_joint']
    wheel_separation: 0.1
    wheel_radius: 0.024

    use_stamped_vel: False

ears_controller:
  ros__parameters:
    joints:
      - right_ear_joint
      - left_ear_joint